### ISSUE TITLE
deadlock when exiting after pipewire has been stopped

### ISSUE THREAD

**Issue by pobrn** [wwmm/easyeffects#2394]
### EasyEffects Version

35f7ef57203e531a90a0dcea55d334f594cb66d7

### What package are you using?

Other (specify below)

### Distribution

Manjaro

### Describe the bug

Easyeffects seems to run into some kind of deadlock when I want to exit it after pipewire has been stopped. The window disappears but process keeps running.

### Expected Behavior

Easyeffects exist cleanly.

### Debug Log

<details><summary>call stacks</summary><br/>

```
Thread 7 (Thread 0x7f52d67ec6c0 (LWP 541981) "easyeffects"):
#0  0x00007f52e8f21266 in epoll_wait (epfd=26, events=0x7f52d67eb8a0, maxevents=32, timeout=-1) at ../sysdeps/unix/sysv/linux/epoll_wait.c:30
#1  0x00007f52dc084c39 in impl_pollfd_wait () at /usr/lib/spa-0.2/support/libspa-support.so
#2  0x00007f52dc0774fd in loop_iterate () at /usr/lib/spa-0.2/support/libspa-support.so
#3  0x00007f52eb935892 in do_loop () at /usr/lib/libpipewire-0.3.so.0
#4  0x00007f52e8e9d44b in start_thread (arg=<optimized out>) at pthread_create.c:444
#5  0x00007f52e8f20e40 in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:81

Thread 6 (Thread 0x7f52d7af66c0 (LWP 541980) "ee-pipewire-thr"):
#0  0x00007f52e8f21266 in epoll_wait (epfd=21, events=0x7f52d7af58b0, maxevents=32, timeout=-1) at ../sysdeps/unix/sysv/linux/epoll_wait.c:30
#1  0x00007f52dc084c39 in impl_pollfd_wait () at /usr/lib/spa-0.2/support/libspa-support.so
#2  0x00007f52dc0774fd in loop_iterate () at /usr/lib/spa-0.2/support/libspa-support.so
#3  0x00007f52eb979155 in do_loop () at /usr/lib/libpipewire-0.3.so.0
#4  0x00007f52e8e9d44b in start_thread (arg=<optimized out>) at pthread_create.c:444
#5  0x00007f52e8f20e40 in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:81

Thread 5 (Thread 0x7f52de3e16c0 (LWP 541970) "gdbus"):
#0  0x00007f52e8f13c0f in __GI___poll (fds=0x604000101e90, nfds=5, timeout=-1) at ../sysdeps/unix/sysv/linux/poll.c:29
#1  0x00007f52eb2568b0 in __interceptor_poll(__sanitizer::__sanitizer_pollfd*, __sanitizer::__sanitizer_nfds_t, int) (fds=0x604000101e90, nfds=5, timeout=-1) at /usr/src/debug/gcc/gcc/libsanitizer/sanitizer_common/sanitizer_common_interceptors.inc:4201
#2  0x00007f52eb16da9f in g_main_context_poll (priority=<optimized out>, n_fds=5, fds=0x604000101e90, timeout=<optimized out>, context=0x60f000007930) at ../glib/glib/gmain.c:4584
#3  g_main_context_iterate.isra.0 (context=0x60f000007930, block=block@entry=1, dispatch=dispatch@entry=1, self=<optimized out>) at ../glib/glib/gmain.c:4271
#4  0x00007f52eb10ff3f in g_main_loop_run (loop=0x60200000fff0) at ../glib/glib/gmain.c:4479
#5  0x00007f52ea60828c in gdbus_shared_thread_func (user_data=0x603000019300) at ../glib/gio/gdbusprivate.c:284
#6  0x00007f52eb142cc5 in g_thread_proxy (data=0x607000007c60) at ../glib/glib/gthread.c:831
#7  0x00007f52e8e9d44b in start_thread (arg=<optimized out>) at pthread_create.c:444
#8  0x00007f52e8f20e40 in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:81

Thread 4 (Thread 0x7f52e02826c0 (LWP 541969) "dconf worker"):
#0  0x00007f52e8f13c0f in __GI___poll (fds=0x60200000d010, nfds=1, timeout=-1) at ../sysdeps/unix/sysv/linux/poll.c:29
#1  0x00007f52eb2568b0 in __interceptor_poll(__sanitizer::__sanitizer_pollfd*, __sanitizer::__sanitizer_nfds_t, int) (fds=0x60200000d010, nfds=1, timeout=-1) at /usr/src/debug/gcc/gcc/libsanitizer/sanitizer_common/sanitizer_common_interceptors.inc:4201
#2  0x00007f52eb16da9f in g_main_context_poll (priority=<optimized out>, n_fds=1, fds=0x60200000d010, timeout=<optimized out>, context=0x60f000000c70) at ../glib/glib/gmain.c:4584
#3  g_main_context_iterate.isra.0 (context=context@entry=0x60f000000c70, block=block@entry=1, dispatch=dispatch@entry=1, self=<optimized out>) at ../glib/glib/gmain.c:4271
#4  0x00007f52eb10e032 in g_main_context_iteration (context=context@entry=0x60f000000c70, may_block=may_block@entry=1) at ../glib/glib/gmain.c:4343
#5  0x00007f52e1bd9fde in dconf_gdbus_worker_thread (user_data=0x60f000000c70) at ../dconf/gdbus/dconf-gdbus-thread.c:82
#6  0x00007f52eb142cc5 in g_thread_proxy (data=0x607000005f80) at ../glib/glib/gthread.c:831
#7  0x00007f52e8e9d44b in start_thread (arg=<optimized out>) at pthread_create.c:444
#8  0x00007f52e8f20e40 in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:81

Thread 3 (Thread 0x7f52e0a916c0 (LWP 541968) "pool-spawner"):
#0  syscall () at ../sysdeps/unix/sysv/linux/x86_64/syscall.S:38
#1  0x00007f52eb165b85 in g_cond_wait (cond=0x6060000057e8, mutex=0x6060000057e0) at ../glib/glib/gthread-posix.c:1475
#2  0x00007f52eb0db094 in g_async_queue_pop_intern_unlocked (queue=0x6060000057e0, wait=1, end_time=-1) at ../glib/glib/gasyncqueue.c:425
#3  0x00007f52eb14524e in g_thread_pool_spawn_thread (data=<optimized out>) at ../glib/glib/gthreadpool.c:311
#4  0x00007f52eb142cc5 in g_thread_proxy (data=0x607000005c00) at ../glib/glib/gthread.c:831
#5  0x00007f52e8e9d44b in start_thread (arg=<optimized out>) at pthread_create.c:444
#6  0x00007f52e8f20e40 in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:81

Thread 2 (Thread 0x7f52e24176c0 (LWP 541967) "gmain"):
#0  0x00007f52e8f13c0f in __GI___poll (fds=0x602000008030, nfds=2, timeout=-1) at ../sysdeps/unix/sysv/linux/poll.c:29
#1  0x00007f52eb2568b0 in __interceptor_poll(__sanitizer::__sanitizer_pollfd*, __sanitizer::__sanitizer_nfds_t, int) (fds=0x602000008030, nfds=2, timeout=-1) at /usr/src/debug/gcc/gcc/libsanitizer/sanitizer_common/sanitizer_common_interceptors.inc:4201
#2  0x00007f52eb16da9f in g_main_context_poll (priority=<optimized out>, n_fds=2, fds=0x602000008030, timeout=<optimized out>, context=0x60f0000004f0) at ../glib/glib/gmain.c:4584
#3  g_main_context_iterate.isra.0 (context=context@entry=0x60f0000004f0, block=block@entry=1, dispatch=dispatch@entry=1, self=<optimized out>) at ../glib/glib/gmain.c:4271
#4  0x00007f52eb10e032 in g_main_context_iteration (context=0x60f0000004f0, may_block=may_block@entry=1) at ../glib/glib/gmain.c:4343
#5  0x00007f52eb10e082 in glib_worker_main (data=<optimized out>) at ../glib/glib/gmain.c:6455
#6  0x00007f52eb142cc5 in g_thread_proxy (data=0x607000004150) at ../glib/glib/gthread.c:831
#7  0x00007f52e8e9d44b in start_thread (arg=<optimized out>) at pthread_create.c:444
#8  0x00007f52e8f20e40 in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:81

Thread 1 (Thread 0x7f52e7861940 (LWP 541964) "easyeffects"):
#0  0x00007f52e8e99f0e in __futex_abstimed_wait_common64 (private=0, cancel=true, abstime=0x0, op=393, expected=0, futex_word=0x61200009e63c) at futex-internal.c:57
#1  __futex_abstimed_wait_common (futex_word=futex_word@entry=0x61200009e63c, expected=expected@entry=0, clockid=clockid@entry=0, abstime=abstime@entry=0x0, private=private@entry=0, cancel=cancel@entry=true) at futex-internal.c:87
#2  0x00007f52e8e99f8f in __GI___futex_abstimed_wait_cancelable64 (futex_word=futex_word@entry=0x61200009e63c, expected=expected@entry=0, clockid=clockid@entry=0, abstime=abstime@entry=0x0, private=private@entry=0) at futex-internal.c:139
#3  0x00007f52e8e9c7a0 in __pthread_cond_wait_common (abstime=0x0, clockid=0, mutex=0x61200009e5e8, cond=0x61200009e610) at pthread_cond_wait.c:503
#4  ___pthread_cond_wait (cond=0x61200009e610, mutex=0x61200009e5e8) at pthread_cond_wait.c:618
#5  0x00007f52eb977a9b in pw_thread_loop_wait () at /usr/lib/libpipewire-0.3.so.0
#6  0x0000563b25d0d497 in PipeManager::sync_wait_unlock() const (this=0x61e000002480) at ../src/pipe_manager.cpp:1787
#7  0x0000563b2609fabc in TestSignals::~TestSignals() (this=0x6260002e2100, __in_chrg=<optimized out>) at ../src/test_signals.cpp:212
#8  0x0000563b2609fc60 in TestSignals::~TestSignals() (this=0x6260002e2100, __in_chrg=<optimized out>) at ../src/test_signals.cpp:213
#9  0x0000563b25da8232 in std::default_delete<TestSignals>::operator()(TestSignals*) const (this=0x6080003c8228, __ptr=0x6260002e2100) at /usr/include/c++/13.1.1/bits/unique_ptr.h:99
#10 0x0000563b25d9e7d5 in std::unique_ptr<TestSignals, std::default_delete<TestSignals> >::~unique_ptr() (this=0x6080003c8228, __in_chrg=<optimized out>) at /usr/include/c++/13.1.1/bits/unique_ptr.h:404
#11 0x0000563b25d9d583 in ui::pipe_manager_box::Data::~Data() (this=0x6080003c8220, __in_chrg=<optimized out>) at ../src/pipe_manager_box.cpp:28
#12 0x0000563b25d744bf in ui::pipe_manager_box::finalize(_GObject*) (object=0x6170000564e0) at ../src/pipe_manager_box.cpp:766
#13 0x00007f52eb00d8b4 in g_object_unref (_object=0x6170000564e0) at ../glib/gobject/gobject.c:3938
#14 g_object_unref (_object=0x6170000564e0) at ../glib/gobject/gobject.c:3802
#15 0x00007f52ea4054fc in stack_remove (self=0x614000044d90, child=0x6170000564e0, in_dispose=1) at ../libadwaita/src/adw-view-stack.c:867
#16 0x00007f52ea4055bd in adw_view_stack_dispose (object=0x614000044d90) at ../libadwaita/src/adw-view-stack.c:1009
#17 0x00007f52eb00d7e3 in g_object_unref (_object=0x614000044d90) at ../glib/gobject/gobject.c:3891
#18 g_object_unref (_object=0x614000044d90) at ../glib/gobject/gobject.c:3802
#19 0x00007f52eb0fa297 in g_hash_table_remove_internal (notify=1, key=0x6020001522d0, hash_table=0x6080003a3920) at ../glib/glib/ghash.c:1775
#20 g_hash_table_remove (hash_table=0x6080003a3920, key=0x6020001522d0) at ../glib/glib/ghash.c:1803
#21 0x00007f52eaa6880a in gtk_widget_real_destroy (object=0x617000053c00) at ../gtk/gtk/gtkwidget.c:7572
#22 gtk_widget_dispose (object=0x617000053c00) at ../gtk/gtk/gtkwidget.c:7435
#23 0x00007f52ea8aff28 in gtk_application_window_dispose (object=0x617000053c00) at ../gtk/gtk/gtkapplicationwindow.c:618
#24 0x0000563b251ddc6e in ui::application_window::dispose(_GObject*) (object=0x617000053c00) at ../src/application_ui.cpp:208
#25 0x00007f52eb00d7e3 in g_object_unref (_object=0x617000053c00) at ../glib/gobject/gobject.c:3891
#26 g_object_unref (_object=0x617000053c00) at ../glib/gobject/gobject.c:3802
#27 0x00007f52eac9969d in gtk_widget_stack_free_elements (end=<optimized out>, start=<optimized out>) at ../gtk/gdk/gdkarrayimpl.c:95
#28 gtk_widget_stack_clear (self=0x7ffcc13086d0) at ../gtk/gdk/gdkarrayimpl.c:104
#29 gtk_propagate_event_internal.isra.0 (widget=0x6140000897b0, event=0x6070004a1da0, topmost=<optimized out>) at ../gtk/gtk/gtkmain.c:1965
#30 0x00007f52ea97d6ed in gtk_main_do_event (event=0x6070004a1da0) at ../gtk/gtk/gtkmain.c:1698
#31 0x00007f52eaa6fd2c in surface_event () at ../gtk/gtk/gtkwindow.c:4748
#32 0x00007f52ea8a8ebd in _gtk_marshal_BOOLEAN__OBJECT (closure=0x607000253c80, return_value=0x7ffcc1308a00, param_values=0x7ffcc1308a60, marshal_data=<optimized out>, invocation_hint=<optimized out>, n_param_values=<optimized out>) at gtk/gtkmarshalers.c:830
#33 0x00007f52eac37df3 in _gdk_marshal_BOOLEAN__POINTER (marshal_data=0x0, invocation_hint=<optimized out>, param_values=0x7ffcc1308a60, n_param_values=2, return_value=0x7ffcc1308a00, closure=0x607000253c80) at gdk/gdkmarshalers.c:244
#34 gdk_surface_event_marshaller (closure=0x607000253c80, return_value=0x7ffcc1308a00, n_param_values=2, param_values=0x7ffcc1308a60, invocation_hint=<optimized out>, marshal_data=0x0) at ../gtk/gdk/gdksurface.c:435
#35 0x00007f52eafff6c0 in g_closure_invoke (closure=0x607000253c80, return_value=0x7ffcc1308a00, n_param_values=2, param_values=0x7ffcc1308a60, invocation_hint=0x7ffcc13089e0) at ../glib/gobject/gclosure.c:832
#36 0x00007f52eb02d938 in signal_emit_unlocked_R.isra.0 (node=<optimized out>, detail=detail@entry=0, instance=instance@entry=0x61400008a660, emission_return=emission_return@entry=0x7ffcc1308b70, instance_and_params=instance_and_params@entry=0x7ffcc1308a60) at ../glib/gobject/gsignal.c:3812
#37 0x00007f52eb01e4cc in g_signal_emit_valist (instance=<optimized out>, signal_id=<optimized out>, detail=<optimized out>, var_args=var_args@entry=0x7ffcc1308c20) at ../glib/gobject/gsignal.c:3575
#38 0x00007f52eb01ed34 in g_signal_emit (instance=instance@entry=0x61400008a660, signal_id=<optimized out>, detail=detail@entry=0) at ../glib/gobject/gsignal.c:3622
#39 0x00007f52eac90ac0 in gdk_surface_handle_event.isra.0 (event=0x6070004a1da0) at ../gtk/gdk/gdksurface.c:2956
#40 0x00007f52eac093ee in gdk_event_source_dispatch.lto_priv () at ../gtk/gdk/x11/gdkeventsource.c:418
#41 0x00007f52eb110981 in g_main_dispatch (context=0x60f0000005e0) at ../glib/glib/gmain.c:3460
#42 g_main_context_dispatch (context=0x60f0000005e0) at ../glib/glib/gmain.c:4200
#43 0x00007f52eb16db39 in g_main_context_iterate.isra.0 (context=context@entry=0x60f0000005e0, block=block@entry=1, dispatch=dispatch@entry=1, self=<optimized out>) at ../glib/glib/gmain.c:4276
#44 0x00007f52eb10e032 in g_main_context_iteration (context=context@entry=0x60f0000005e0, may_block=may_block@entry=1) at ../glib/glib/gmain.c:4343
#45 0x00007f52ea5d5ed6 in g_application_run (application=0x613000000300, argc=<optimized out>, argv=0x7ffcc1309368) at ../glib/gio/gapplication.c:2573
#46 0x0000563b2519d5f8 in main(int, char**) (argc=1, argv=0x7ffcc1309368) at ../src/easyeffects.cpp:56
```
</details>

**Comment by wwmm** [comment]
Probably for the same reasons as #1447. We need an elaborated code refactoring to be able to handle the server restart. I have no idea when I will be able to put some efforts on this.

As there is already #1447 we can close this issue.

**Comment by wwmm** [comment]
No problems :-)
